use data_encoding::BASE64URL_NOPAD;
use vault_crypto::{
    Cipher,
    data_cipher::{decrypt_size, encrypted_size},
    decrypt_reader::AsyncDecryptReader,
    encrypt_reader::AsyncEncryptReader,
    errors::DecryptFilenameError,
};

use crate::error::AppError;

/// Thin, application-owned boundary around Koofr's rclone-compatible crypto engine.
///
/// The wrapped implementation is pinned to koofr/vault commit
/// 17c95914dbc25f42f71869d1878f58a6675474ce.
pub struct VaultCipher {
    inner: Cipher,
}

impl VaultCipher {
    pub fn new(safe_key: &str, salt: Option<&str>) -> Self {
        Self {
            inner: Cipher::new(safe_key, salt),
        }
    }

    pub fn encrypt_name(&self, name: &str) -> String {
        self.inner.encrypt_filename(name)
    }

    pub fn decrypt_name(&self, name: &str) -> Result<String, AppError> {
        self.inner
            .decrypt_filename(name)
            .map_err(|_| AppError::VaultCrypto)
    }

    pub fn encrypt_reader<R>(&self, reader: R) -> AsyncEncryptReader<R> {
        self.inner.encrypt_reader_async(reader)
    }

    pub fn decrypt_reader<R>(&self, reader: R) -> AsyncDecryptReader<R> {
        self.inner.decrypt_reader_async(reader)
    }

    pub fn encrypted_size(plain_size: u64) -> Result<u64, AppError> {
        let size =
            i64::try_from(plain_size).map_err(|_| AppError::InvalidInput("vault file size"))?;
        u64::try_from(encrypted_size(size))
            .map_err(|_| AppError::InvalidInput("vault encrypted file size"))
    }

    pub fn decrypted_size(cipher_size: i64) -> Result<i64, AppError> {
        decrypt_size(cipher_size).map_err(|_| AppError::VaultCrypto)
    }

    pub fn validates(&self, validator: &str, encrypted_validator: &str) -> Result<bool, AppError> {
        if let Some(encoded) = encrypted_validator.strip_prefix("v2:") {
            let ciphertext = BASE64URL_NOPAD
                .decode(encoded.as_bytes())
                .map_err(|_| AppError::VaultCrypto)?;
            let mut plaintext = Vec::new();
            if self
                .inner
                .decrypt_data(&ciphertext, &mut plaintext)
                .is_err()
            {
                return Ok(false);
            }
            return Ok(plaintext == validator.as_bytes());
        }

        match self.inner.decrypt_filename(encrypted_validator) {
            Ok(decrypted) => Ok(decrypted == validator),
            Err(DecryptFilenameError::DecryptError | DecryptFilenameError::UnicodeError(_)) => {
                Ok(false)
            }
            Err(_) => Err(AppError::VaultCrypto),
        }
    }

    pub fn generate_validator(&self) -> Result<(String, String), AppError> {
        let validator = uuid::Uuid::new_v4().to_string();
        let mut encrypted = Vec::new();
        self.inner
            .encrypt_data(validator.as_bytes(), &mut encrypted)
            .map_err(|_| AppError::VaultCrypto)?;
        Ok((
            validator,
            format!("v2:{}", BASE64URL_NOPAD.encode(&encrypted)),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::VaultCipher;

    #[test]
    fn matches_rclone_filename_vectors() {
        let cipher = VaultCipher::new("testpassword", None);
        let encrypted = cipher.encrypt_name("testfilename");
        assert_eq!(encrypted, "mvedi866srqc97sl5948oaej2g");
        assert_eq!(
            cipher.decrypt_name(&encrypted).expect("decrypt filename"),
            "testfilename"
        );
    }

    #[test]
    fn round_trips_unicode_names() {
        let cipher = VaultCipher::new("一次性测试密码", Some("一次性测试 salt"));
        let encrypted = cipher.encrypt_name("资料📁-č.txt");
        // Generated independently with rclone cryptdecode --reverse.
        assert_eq!(
            encrypted,
            "6c3iuguatifq0qvrp03fdbrtarj0cl7mrklk66d40o529vlp9o70"
        );
        assert_eq!(
            cipher.decrypt_name(&encrypted).expect("decrypt unicode"),
            "资料📁-č.txt"
        );
    }

    #[test]
    fn matches_rclone_content_vector_and_rejects_tampering() {
        let cipher = VaultCipher::new("testpassword", None);
        // Generated by rclone 1.60 and published in koofr/vault's vault-crypto tests.
        let mut encrypted = vec![
            82, 67, 76, 79, 78, 69, 0, 0, 209, 27, 246, 23, 134, 105, 131, 148, 3, 49, 228, 74,
            200, 43, 245, 170, 123, 102, 24, 137, 45, 77, 53, 115, 206, 216, 221, 4, 40, 177, 52,
            14, 5, 190, 84, 192, 246, 157, 207, 154, 11, 178, 94, 181, 135, 59, 240, 115,
        ];
        let mut decrypted = Vec::new();
        cipher
            .inner
            .decrypt_data(&encrypted, &mut decrypted)
            .expect("decrypt rclone vector");
        assert_eq!(decrypted, b"testdata");

        encrypted[40] ^= 1;
        decrypted.clear();
        assert!(
            cipher
                .inner
                .decrypt_data(&encrypted, &mut decrypted)
                .is_err()
        );
    }

    #[test]
    fn matches_rclone_content_size_boundaries() {
        assert_eq!(VaultCipher::encrypted_size(0).expect("empty"), 32);
        assert_eq!(VaultCipher::encrypted_size(1).expect("one byte"), 49);
        assert_eq!(
            VaultCipher::encrypted_size(65_536).expect("one block"),
            65_584
        );
        assert_eq!(
            VaultCipher::encrypted_size(65_537).expect("two blocks"),
            65_601
        );
    }

    #[test]
    fn validates_legacy_and_current_password_validators() {
        let cipher = VaultCipher::new("testpassword", None);
        assert!(
            cipher
                .validates(
                    "d645d972-d7f4-4577-bec6-b52652c025c9",
                    "lb96gl718rmaq911ehuan90tu6ta5sg6k38fpd4hsj91p4h0tvd5ouk37663f9jacrl9eaq4depri",
                )
                .expect("validate v1")
        );
        assert!(
            cipher
                .validates(
                    "508ddd3f-f18e-4514-932b-b2c1f0c8b291",
                    "v2:UkNMT05FAAA-YjvGKKxTpiFekFYVMNO2UnG2u-Z16MMHAB-ipQYycVTmPSNk0mbnYeZrZ2I-Kh0lTmh4Kt2UxhdYWEXd9YQvyODrWMWWHZaLhL7e",
                )
                .expect("validate v2")
        );
    }
}
